### PR TITLE
Add the possibility to download all startup logs

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Add the possibility to download all startup logs.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16063

Screenshot from 2020-03-24 02-18-20

### CODE REVIEW

**Comment by sleshchenko** [comment]
I wonder if it would look a bit better if we place `Download logs` below the text

**Comment by sleshchenko** [comment]
`Press F5 to try again or click here to try again.` Is it shown when debug output is already enabled, right? Maybe it makes sense to change it -> `Press F5 or click here to try again.`

**Comment by olexii4** [comment]
@sleshchenko 

Screenshot from 2020-03-25 14-14-19
Screenshot from 2020-03-25 14-14-19

**Comment by sleshchenko** [comment]
I like the first variant more

**Comment by olexii4** [comment]
Screenshot from 2020-03-25 14-26-56

Already done!

**Pull request merged**
